empty_bin_station_1:
  orientation:
    w: 0.6497224126335203
    x: 0.0
    y: 0.0
    z: 0.7601715507184399
  position:
    x: 3.5557618364511594
    y: -0.9085470437716081
    z: 0.0
home:
  orientation:
    w: 0.966298571511887
    x: 0.0
    y: 0.0
    z: -0.257423912436445
  position:
    x: 1.8259518731203181
    y: -6.798664841984376
    z: 0.0
xd38r_station_1:
  orientation:
    w: 0.08250324862199948
    x: 0.0
    y: 0.0
    z: 0.9965907956462454
  position:
    x: 5.1927590975736395
    y: -4.964987026117389
    z: 0.0
